### ISSUE TITLE
/bin/armador operation not permitted during build phase 

### ISSUE THREAD

**Issue by quantum-fusion** [travelaudience/armador#20]
### Expected Behaviour

go build -o $GOPATH/bin/armador

### Actual Behaviour
go build github.com/travelaudience/armador: open /bin/armador: operation not permitted

**Comment by jeff-knurek** [comment]
hmm, I have an idea to the problem, but i need more info

what's the `go version`?
which OS are you on?

**Comment by quantum-fusion** [comment]
MacBook-Pro:~ quantum-fusion$ go version
go version go1.12 darwin/amd64

MACOS Catalina 10.15.1

**Comment by jeff-knurek** [comment]
and can you confirm if running `go build` in the armador code directory works ok? 
the end result of that command should be a binary file called `armador` that's approx 13MB in size

**Comment by quantum-fusion** [comment]
go build
MacBook-Pro:~/Desktop/armador-master quantum-fusion$ ls
LICENSE		armador		docs		go.sum		main.go
README.md	cmd		go.mod		internal

**Comment by quantum-fusion** [comment]
yes it builds, with go build

**Comment by jeff-knurek** [comment]
so then it's the copy into `$GOPATH/bin` where there seems to be a permission problem - cause the `-o $GOPATH/bin/armador` option is to skip saving it into the current path, and instead saving it into an executable path 

check `echo $GOPATH`, and then see if you can `cp ~/Desktop/armador-master quantum-fusion/armador [TO_THE_PATH_FROM_ECHO]`

**Comment by quantum-fusion** [comment]
I don't have a $GOPATH variable defined.

So, a simple copy worked.

which armador
/usr/local/bin/armador
MacBook-Pro:~/Desktop/armador-master quantum-fusion$ which go
/usr/local/bin/go

**Comment by quantum-fusion** [comment]
armador
A longer description that spans multiple lines and likely contains
examples and usage of using your application. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.

Usage:
  armador [command]

Available Commands:
  clean       Remove cache and temp files
  create      Create a dev env
  delete      Tear down an existing dev env
  helm        Manage your local helm install
  help        Help about any command
  list        List the environments currently running
  recreate    Use a cache file to re-create an env with the same settings
  snapshot    Create a snapshot of a running env, using helm charts/values save to config file.
  update      Update a dev env

Flags:
      --config string   config file (default is $HOME/.armador.yaml)
  -h, --help            help for armador
  -v, --verbose         verbose output

Use "armador [command] --help" for more information about a command.

**Comment by jeff-knurek** [comment]
success!

I'm going to close this issue. If you can think of a good way to update the README instructions to account for this potential problem, please submit a PR :)

----
looks like we need to clean up the default message, this came by default from the library being used under the hood:
```
A longer description that spans multiple lines and likely contains
examples and usage of using your application. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.
```

**Comment by quantum-fusion** [comment]
go build

ls armador

which go

<see path>

cp armador /<see path/bin> 

which armador

<should be same as see path>
